import { InMemoryDbService, RequestInfo } from 'angular-in-memory-web-api';
import { Observable } from 'rxjs';

import { Customer } from './pages/customers/shared/customer.model';
import { Expert } from './pages/experts/shared/expert.model';
import { InvoiceEntries } from './pages/invoice-entries/shared/invoice-entries.model';
import { Seller } from './pages/sellers/shared/seller.model';
import { State } from './shared/models/state.model';
export class InMemoryDatabase implements InMemoryDbService {
  createDb(reqInfo?: RequestInfo): {} | Observable<{}> | Promise<{}> {
    const sellers: Seller[] = [
      {
        id: 1,
        name: 'MEREDITH GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 10',
        zipCode: '00000111',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 2,
        name: 'ELLIS GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 11',
        zipCode: '00000112',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: false,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 3,
        name: 'LEXIE GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 12',
        zipCode: '00000113',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: false,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 4,
        name: 'DEREK SHEPHERD',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 13',
        zipCode: '00000114',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 5,
        name: 'MARK SLOAN',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 14',
        zipCode: '00000115',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: false,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 6,
        name: 'CRISTINA YANG',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 15',
        zipCode: '00000116',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 7,
        name: 'ALEX KAREV',
        state: 'RJ',
        city: 'Rio de Janeiro',
        address: 'RUA TESTE, 16',
        zipCode: '00000117',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 8,
        name: 'GEORGE O´MALLEY',
        state: 'MG',
        city: 'Belo Horizonte',
        address: 'RUA TESTE, 17',
        zipCode: '00000118',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: false,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 9,
        name: 'ISOBEL STEVES',
        state: 'SP',
        city: 'Campinas',
        address: 'RUA TESTE, 18',
        zipCode: '00000119',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 10,
        name: 'APRIL KEPNER',
        state: 'MT',
        city: 'Campo Grande',
        address: 'RUA TESTE, 19',
        zipCode: '00000120',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 11,
        name: 'OWEN HUNT',
        state: 'AM',
        city: 'Manaus',
        address: 'RUA TESTE, 20',
        zipCode: '00000121',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 12,
        name: 'ARIZONA ROBBINS',
        state: 'BA',
        city: 'Salvador',
        address: 'RUA TESTE, 21',
        zipCode: '00000122',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 13,
        name: 'ADDISON MONTGOMERY',
        state: 'PR',
        city: 'Curitiba',
        address: 'RUA TESTE, 22',
        zipCode: '00000123',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 14,
        name: 'MIRANDA BAILEY',
        state: 'BA',
        city: 'Salvador',
        address: 'RUA TESTE, 23',
        zipCode: '00000124',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 15,
        name: 'JO WILSON',
        state: 'AC',
        city: 'Rio Branco',
        address: 'RUA TESTE, 24',
        zipCode: '00000125',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 16,
        name: 'CALLIE TORRES',
        state: 'RS',
        city: 'Porto Alegre',
        address: 'RUA TESTE, 25',
        zipCode: '00000126',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 17,
        name: 'JACKSON AVERY',
        state: 'RS',
        city: 'Gramado',
        address: 'RUA TESTE, 26',
        zipCode: '00000127',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 18,
        name: 'CATHERINE AVERY',
        state: 'RS',
        city: 'Gramado',
        address: 'RUA TESTE, 27',
        zipCode: '00000128',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 19,
        name: 'PRESTON BURKE',
        state: 'RJ',
        city: 'Parati',
        address: 'RUA TESTE, 28',
        zipCode: '00000129',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 20,
        name: 'TEDDY ALTMAN',
        state: 'SC',
        city: 'Florianopolis',
        address: 'RUA TESTE, 29',
        zipCode: '00000130',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 21,
        name: 'RICHARD WEBBER',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 30',
        zipCode: '00000131',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 22,
        name: 'ADELE WEBBER',
        state: 'SP',
        city: 'São Caetano',
        address: 'RUA TESTE, 31',
        zipCode: '00000132',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: false,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 23,
        name: 'ERICA HAHN',
        state: 'SC',
        city: 'Florianopolis',
        address: 'RUA TESTE, 32',
        zipCode: '00000133',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 24,
        name: 'BEM WARREM',
        state: 'BA',
        city: 'Porto Seguro',
        address: 'RUA TESTE, 33',
        zipCode: '00000134',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 25,
        name: 'LEAH MURPHY',
        state: 'MG',
        city: 'Belo Horizonte',
        address: 'RUA TESTE, 34',
        zipCode: '00000135',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
      {
        id: 26,
        name: 'SHANE ROSS',
        state: 'PE',
        city: 'RecIfe',
        address: 'RUA TESTE, 35',
        zipCode: '00000136',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        customerId: '1',
        customerName: 'Grey Sloan Memorial Hospital',
      },
    ];

    const experts: Expert[] = [
      { id: 1, name: 'Gregory House', regionalId: '3', isActive: true },
      { id: 2, name: 'Lisa Cuddy', regionalId: '2', isActive: true },
      { id: 3, name: 'Lawrence Kutner', regionalId: '3', isActive: true },
      { id: 4, name: 'Robert Chase', regionalId: '1', isActive: true },
      { id: 5, name: 'James Wilson', regionalId: '3', isActive: true },
      { id: 6, name: 'Eric Foreman', regionalId: '2', isActive: true },
      { id: 7, name: 'Remy Hadley Thirteen', regionalId: '1', isActive: true },
      { id: 8, name: 'Chris Taub', regionalId: '1', isActive: true },
    ];

    const states: State[] = [
      { value: 'AC', text: 'ACRE' },
      { value: 'AL', text: 'ALAGOAS' },
      { value: 'AP', text: 'AMAPÁ' },
      { value: 'AM', text: 'AMAZONAS' },
      { value: 'BA', text: 'BAHIA' },
      { value: 'CE', text: 'CEARÁ' },
      { value: 'DF', text: 'DISTRITO FEDERAL' },
      { value: 'ES', text: 'ESPIRITO SANTOS' },
      { value: 'GO', text: 'GOIÁS' },
      { value: 'MA', text: 'MARANHÃO' },
      { value: 'MT', text: 'MATO GROSSO' },
      { value: 'MS', text: 'MATO GROSSO DO SUL' },
      { value: 'MG', text: 'MINAS GERAIS' },
      { value: 'PA', text: 'PARÁ' },
      { value: 'PB', text: 'PARAÍBA' },
      { value: 'PR', text: 'PARANÁ' },
      { value: 'PE', text: 'PERNANBUCO' },
      { value: 'PI', text: 'PIAUÍ' },
      { value: 'RJ', text: 'RIO DE JANEIRO' },
      { value: 'RN', text: 'RIO GRANDE DO NORTE' },
      { value: 'RS', text: 'RIO GRANDE DO SUL' },
      { value: 'RO', text: 'RONDÔNIA' },
      { value: 'RR', text: 'RORAIMA' },
      { value: 'SC', text: 'SANTA CATARINA' },
      { value: 'SP', text: 'SÃO PAULO' },
      { value: 'SE', text: 'SERGIPE' },
      { value: 'TO', text: 'TOCANTINS' },
    ];

    const customers: Customer[] = [
      {
        id: 1,
        name: 'Grey Sloan Memorial Hospital',
        expertId: '2',
        state: 'SP',
        city: 'SÃO PAULO',
        neighborhood: 'BELA VISTA',
        document: 44427480000147,
        isActive: true,
      },
      {
        id: 2,
        name: 'San Antonio Medical Center',
        expertId: '3',
        state: 'SP',
        city: 'SÃO PAULO',
        neighborhood: 'GRANJA JULIETA',
        document: 17789684000155,
        isActive: true,
      },
      {
        id: 3,
        name: 'Princeton-Plainsboro Teaching Hospital',
        expertId: '1',
        state: 'SP',
        city: 'SÃO PAULO',
        neighborhood: 'GRANJA JULIETA',
        document: 43418925000160,
        isActive: true,
      },
      {
        id: 4,
        name: 'San Jose St. Bonaventure Hospital.',
        expertId: '4',
        state: 'MG',
        city: 'BELO HORIZONTE',
        neighborhood: 'PANPULHA',
        document: 74937887000185,
        isActive: true,
      },
      {
        id: 5,
        name: 'Mercy West',
        expertId: '4',
        state: 'RJ',
        city: 'RIO DE JANEIRO',
        neighborhood: 'IPANEMA',
        document: 47267748000119,
        isActive: false,
      },
      {
        id: 6,
        name: 'Hospital naval de Pearl Harbor',
        expertId: '4',
        state: 'BA',
        city: 'SALVADOR',
        neighborhood: 'CENTRO',
        document: 95374959000101,
        isActive: true,
      },
      {
        id: 7,
        name: 'Chicago Medical Center',
        expertId: '4',
        state: 'DF',
        city: 'BRASILIA',
        neighborhood: 'LOTE 14',
        document: 36428154000126,
        isActive: true,
      },
      {
        id: 8,
        name: 'Hospital Nossa Senhora das Dores',
        expertId: '4',
        state: 'RJ',
        city: 'RIO DE JANEIRO',
        neighborhood: 'COPACABANA',
        document: 52083078000110,
        isActive: true,
      },
      {
        id: 9,
        name: 'Seattle Grace Hospital',
        expertId: '1',
        state: 'SP',
        city: 'SÃO PAULO',
        neighborhood: 'BELA VISTA',
        document: 23044078000103,
        isActive: false,
      },
      {
        id: 10,
        name: 'Hospital Salve',
        expertId: '1',
        state: 'SP',
        city: 'SÃO PAULO',
        neighborhood: 'PIRITUBA',
        document: 38318511000129,
        isActive: true,
      },
      {
        id: 11,
        name: 'Hospital Lima',
        expertId: '4',
        state: 'BA',
        city: 'IGATU',
        neighborhood: 'CENTRO',
        document: 25671535000115,
        isActive: true,
      },
    ];

    const invoices: InvoiceEntries[] = [
      {
        id: 1,
        sellerId: '1',
        sellerName: 'MEREDITH GREY',
        customerName: 'Grey Sloan Memorial Hospital',
        document: '123456789',
        issueDate: new Date(),
        buyerName: 'DARTH VADER',
        amount: 90,
        items: [
          {
            id: 1,
            product: 'TELHA ONDUVILA',
            unitPrice: 45,
            quantity: 2,
          },
        ],
      },
    ];

    return { sellers, experts, states, customers, invoices };
  }
}
