import { Expert } from './pages/experts/shared/expert.model';
import { InMemoryDbService, RequestInfo } from 'angular-in-memory-web-api';
import { Observable } from 'rxjs';
import { Seller } from './pages/sellers/shared/seller.model';
import { State } from './shared/models/state.model';

export class InMemoryDatabase implements InMemoryDbService {
  createDb(reqInfo?: RequestInfo): {} | Observable<{}> | Promise<{}> {
    const sellers: Seller[] = [
      {
        id: 1,
        name: 'MEREDITH GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 10',
        zipCode: '00000111',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 2,
        name: 'ELLIS GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 11',
        zipCode: '00000112',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 3,
        name: 'LEXIE GREY',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 12',
        zipCode: '00000113',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 4,
        name: 'DEREK SHEPHERD',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 13',
        zipCode: '00000114',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 5,
        name: 'MARK SLOAN',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 14',
        zipCode: '00000115',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 6,
        name: 'CRISTINA YANG',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 15',
        zipCode: '00000116',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 7,
        name: 'ALEX KAREV',
        state: 'RJ',
        city: 'Rio de Janeiro',
        address: 'RUA TESTE, 16',
        zipCode: '00000117',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 8,
        name: 'GEORGE O´MALLEY',
        state: 'MG',
        city: 'Belo Horizonte',
        address: 'RUA TESTE, 17',
        zipCode: '00000118',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 9,
        name: 'ISOBEL STEVES',
        state: 'SP',
        city: 'Campinas',
        address: 'RUA TESTE, 18',
        zipCode: '00000119',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 10,
        name: 'APRIL KEPNER',
        state: 'MT',
        city: 'Campo Grande',
        address: 'RUA TESTE, 19',
        zipCode: '00000120',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 11,
        name: 'OWEN HUNT',
        state: 'AM',
        city: 'Manaus',
        address: 'RUA TESTE, 20',
        zipCode: '00000121',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 12,
        name: 'ARIZONA ROBBINS',
        state: 'BA',
        city: 'Salvador',
        address: 'RUA TESTE, 21',
        zipCode: '00000122',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 13,
        name: 'ADDISON MONTGOMERY',
        state: 'PR',
        city: 'Curitiba',
        address: 'RUA TESTE, 22',
        zipCode: '00000123',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 14,
        name: 'MIRANDA BAILEY',
        state: 'BA',
        city: 'Salvador',
        address: 'RUA TESTE, 23',
        zipCode: '00000124',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 15,
        name: 'JO WILSON',
        state: 'AC',
        city: 'Rio Branco',
        address: 'RUA TESTE, 24',
        zipCode: '00000125',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 16,
        name: 'CALLIE TORRES',
        state: 'RS',
        city: 'Porto Alegre',
        address: 'RUA TESTE, 25',
        zipCode: '00000126',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 17,
        name: 'JACKSON AVERY',
        state: 'RS',
        city: 'Gramado',
        address: 'RUA TESTE, 26',
        zipCode: '00000127',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 18,
        name: 'CATHERINE AVERY',
        state: 'RS',
        city: 'Gramado',
        address: 'RUA TESTE, 27',
        zipCode: '00000128',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 19,
        name: 'PRESTON BURKE',
        state: 'RJ',
        city: 'Parati',
        address: 'RUA TESTE, 28',
        zipCode: '00000129',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 20,
        name: 'TEDDY ALTMAN',
        state: 'SC',
        city: 'Florianopolis',
        address: 'RUA TESTE, 29',
        zipCode: '00000130',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 21,
        name: 'RICHARD WEBBER',
        state: 'SP',
        city: 'São Paulo',
        address: 'RUA TESTE, 30',
        zipCode: '00000131',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 22,
        name: 'ADELE WEBBER',
        state: 'SP',
        city: 'São Caetano',
        address: 'RUA TESTE, 31',
        zipCode: '00000132',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 23,
        name: 'ERICA HAHN',
        state: 'SC',
        city: 'Florianopolis',
        address: 'RUA TESTE, 32',
        zipCode: '00000133',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 24,
        name: 'BEM WARREM',
        state: 'BA',
        city: 'Porto Seguro',
        address: 'RUA TESTE, 33',
        zipCode: '00000134',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 25,
        name: 'LEAH MURPHY',
        state: 'MG',
        city: 'Belo Horizonte',
        address: 'RUA TESTE, 34',
        zipCode: '00000135',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
      {
        id: 26,
        name: 'SHANE ROSS',
        state: 'PE',
        city: 'RecIfe',
        address: 'RUA TESTE, 35',
        zipCode: '00000136',
        neighborhood: 'VILA TESTE',
        complement: '',
        type: 1,
        document: 44785893052,
        email: '',
        phone: 1133333333,
        isActive: true,
        storeId: 1,
      },
    ];

    const experts: Expert[] = [
      {id: 1, name: 'Gregory House', regionalId: '3', isActive: true},
      {id: 2, name: 'Lisa Cuddy', regionalId: '2', isActive: true},
      {id: 3, name: 'Lawrence Kutner', regionalId: '3', isActive: true},
      {id: 4, name: 'Robert Chase', regionalId: '1', isActive: true},
      {id: 5, name: 'James Wilson', regionalId: '3', isActive: true},
      {id: 6, name: 'Eric Foreman', regionalId: '2', isActive: true},
      {id: 7, name: 'Remy Hadley Thirteen', regionalId: '1', isActive: true},
      {id: 8, name: 'Chris Taub', regionalId: '1', isActive: true},
    ];

    const states: State[] = [
      {value: 'AC', text: 'ACRE'},
      {value: 'AL', text: 'ALAGOAS'},
      {value: 'AP', text: 'AMAPÁ'},
      {value: 'AM', text: 'AMAZONAS'},
      {value: 'BA', text: 'BAHIA'},
      {value: 'CE', text: 'CEARÁ'},
      {value: 'DF', text: 'DISTRITO FEDERAL'},
      {value: 'ES', text: 'ESPIRITO SANTOS'},
      {value: 'GO', text: 'GOIÁS'},
      {value: 'MA', text: 'MARANHÃO'},
      {value: 'MT', text: 'MATO GROSSO'},
      {value: 'MS', text: 'MATO GROSSO DO SUL'},
      {value: 'MG', text: 'MINAS GERAIS'},
      {value: 'PA', text: 'PARÁ'},
      {value: 'PB', text: 'PARAÍBA'},
      {value: 'PR', text: 'PARANÁ'},
      {value: 'PE', text: 'PERNANBUCO'},
      {value: 'PI', text: 'PIAUÍ'},
      {value: 'RJ', text: 'RIO DE JANEIRO'},
      {value: 'RN', text: 'RIO GRANDE DO NORTE'},
      {value: 'RS', text: 'RIO GRANDE DO SUL'},
      {value: 'RO', text: 'RONDÔNIA'},
      {value: 'RR', text: 'RORAIMA'},
      {value: 'SC', text: 'SANTA CATARINA'},
      {value: 'SP', text: 'SÃO PAULO'},
      {value: 'SE', text: 'SERGIPE'},
      {value: 'TO', text: 'TOCANTINS'},
    ]

    return { sellers, experts, states };
  }
}
